swagger: "2.0"
info:
    title: Books API
    description: API for managing books
    version: 0.0.1
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /books:
        post:
            tags:
                - book
            summary: create book
            operationId: book#create
            parameters:
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/BookPayload'
                    required:
                        - title
                        - author
                        - cover_url
                        - published_at
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/Book'
                        required:
                            - id
                            - title
                            - author
                            - cover_url
                            - published_at
                "422":
                    description: Unprocessable Entity response.
                    schema:
                        $ref: '#/definitions/BookCreateValidationErrorResponseBody'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/BookCreateInternalErrorResponseBody'
            schemes:
                - http
    /books/{id}:
        get:
            tags:
                - book
            summary: show book
            operationId: book#show
            parameters:
                - name: id
                  in: path
                  description: ID of the book
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Book'
                        required:
                            - id
                            - title
                            - author
                            - cover_url
                            - published_at
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BookShowNotFoundResponseBody'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/BookShowInternalErrorResponseBody'
            schemes:
                - http
        put:
            tags:
                - book
            summary: update book
            operationId: book#update
            parameters:
                - name: id
                  in: path
                  description: ID of the book
                  required: true
                  type: string
                - name: UpdateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/BookUpdateRequestBody'
                    required:
                        - book
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Book'
                        required:
                            - id
                            - title
                            - author
                            - cover_url
                            - published_at
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BookUpdateNotFoundResponseBody'
                "422":
                    description: Unprocessable Entity response.
                    schema:
                        $ref: '#/definitions/BookUpdateValidationErrorResponseBody'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/BookUpdateInternalErrorResponseBody'
            schemes:
                - http
        delete:
            tags:
                - book
            summary: delete book
            operationId: book#delete
            parameters:
                - name: id
                  in: path
                  description: ID of the book
                  required: true
                  type: string
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BookDeleteNotFoundResponseBody'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/BookDeleteInternalErrorResponseBody'
            schemes:
                - http
definitions:
    Book:
        title: Book
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Alan A. A. Donovan
            cover_url:
                type: string
                description: URL of the book cover
                example: https://example.com/cover.jpg
            id:
                type: string
                description: ID of the book
                example: Quia omnis in rem.
            published_at:
                type: string
                description: Publish date of the book
                example: "2023-01-01"
            title:
                type: string
                description: Title of the book
                example: The Go Programming Language
        example:
            author: Alan A. A. Donovan
            cover_url: https://example.com/cover.jpg
            id: Assumenda architecto sapiente nesciunt aut repellendus rerum.
            published_at: "2023-01-01"
            title: The Go Programming Language
        required:
            - id
            - title
            - author
            - cover_url
            - published_at
    BookCreateInternalErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: An internal error occurred while processing the request. (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BookCreateValidationErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: create_ValidationError_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BookDeleteInternalErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: delete_InternalError_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BookDeleteNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: delete_NotFound_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BookPayload:
        title: BookPayload
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Amet iste saepe.
            cover_url:
                type: string
                description: URL of the book cover
                example: Est temporibus voluptatibus occaecati sint.
            published_at:
                type: string
                description: Publish date of the book
                example: "2023-01-01"
            title:
                type: string
                description: Title of the book
                example: Aut occaecati odit tenetur.
        example:
            author: Sint consequuntur.
            cover_url: Alias eos magnam qui quibusdam quas velit.
            published_at: "2023-01-01"
            title: Assumenda sed placeat perferendis quia.
        required:
            - title
            - author
            - cover_url
            - published_at
    BookShowInternalErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: show_InternalError_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BookShowNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: show_NotFound_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BookUpdateInternalErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: update_InternalError_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BookUpdateNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: update_NotFound_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BookUpdateRequestBody:
        title: BookUpdateRequestBody
        type: object
        properties:
            book:
                $ref: '#/definitions/BookPayload'
        example:
            book:
                author: Eos consequuntur tempore.
                cover_url: Eum maiores maxime.
                published_at: "2023-01-01"
                title: At nesciunt deserunt.
        required:
            - book
    BookUpdateValidationErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: update_ValidationError_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
